"""News Sources Table

Revision ID: 115eb3184357
Revises: 
Create Date: 2021-02-13 11:48:55.007380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115eb3184357'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('full_url', sa.String(length=120), nullable=True),
    sa.Column('formatted_url', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_sources_formatted_url'), 'news_sources', ['formatted_url'], unique=True)
    op.create_index(op.f('ix_news_sources_full_url'), 'news_sources', ['full_url'], unique=True)
    op.create_index(op.f('ix_news_sources_name'), 'news_sources', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_sources_name'), table_name='news_sources')
    op.drop_index(op.f('ix_news_sources_full_url'), table_name='news_sources')
    op.drop_index(op.f('ix_news_sources_formatted_url'), table_name='news_sources')
    op.drop_table('news_sources')
    # ### end Alembic commands ###
