"""added category and lang rows to News Source table

Revision ID: 71bdf7fb01d1
Revises: 115eb3184357
Create Date: 2021-02-13 12:07:26.162506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bdf7fb01d1'
down_revision = '115eb3184357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_sources', sa.Column('category', sa.String(length=64), nullable=True))
    op.add_column('news_sources', sa.Column('language', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_news_sources_category'), 'news_sources', ['category'], unique=True)
    op.create_index(op.f('ix_news_sources_language'), 'news_sources', ['language'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_sources_language'), table_name='news_sources')
    op.drop_index(op.f('ix_news_sources_category'), table_name='news_sources')
    op.drop_column('news_sources', 'language')
    op.drop_column('news_sources', 'category')
    # ### end Alembic commands ###
